apiVersion: apps/v1
kind: deployment
metadata: 
  name: conversao-temperatura
spec:
  replicas: 5
  selector:
    matchLabels:
	  app: conversao
    template:
      metadata: 
      labels:
         app: conversao
      spec:
        containers:
        - name: site
          image: marcusbergamo/coversao-temperatura:v1
	      ports: 
	     - containerPort: 80
		 
		 
apiVersion: v1
kind: Service
metadata: 
  name: web-page
spec:
  selector:
    app: conversao
  ports:
    - port: 80
	  protocol: TCP
	  nodePort: 30000
  type: NodePort